"""Each ``ta.*`` equivalent against hand-computed fixtures.

``docs/06_PARITY_TESTS.md`` section 4. The divergence-specific regressions live in
their own files (``test_ema_seeding.py``, ``test_stdev_ddof.py`` and siblings);
this one covers the remaining primitives and the arithmetic that has no
interesting trap attached to it.

Every fixture below is small enough to verify on paper. That is deliberate: a
fixture generated by running the implementation and pasting the output tests only
that the code has not changed, not that it is right.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from azimuth.core import primitives as p

# ── the module's public surface ─────────────────────────────────────────────────

REQUIRED = [
    "ema",
    "rma",
    "rsi",
    "stdev",
    "atr",
    "percentrank",
    "correlation",
    "dmi",
    "pivot_high",
    "pivot_low",
]


@pytest.mark.parametrize("name", REQUIRED)
def test_required_primitive_exists_and_is_exported(name: str):
    """The set named in docs/10_ROADMAP.md M1 and the Task 2 brief."""
    assert hasattr(p, name), f"{name} is missing"
    assert name in p.__all__, f"{name} is not exported"


# ── simple moving average ───────────────────────────────────────────────────────


def test_sma():
    src = pd.Series([1.0, 2.0, 3.0, 4.0, 5.0])
    result = p.sma(src, 3)

    assert result.iloc[:2].isna().all()
    np.testing.assert_allclose(result.iloc[2:], [2.0, 3.0, 4.0], atol=1e-12)


# ── change / rolling sum ────────────────────────────────────────────────────────


def test_change_default_is_one_bar():
    src = pd.Series([1.0, 3.0, 6.0, 10.0])
    result = p.change(src)

    assert pd.isna(result.iloc[0])
    np.testing.assert_allclose(result.iloc[1:], [2.0, 3.0, 4.0], atol=1e-12)


def test_change_over_n_bars():
    src = pd.Series([1.0, 3.0, 6.0, 10.0])
    result = p.change(src, 2)

    assert result.iloc[:2].isna().all()
    np.testing.assert_allclose(result.iloc[2:], [5.0, 7.0], atol=1e-12)


def test_rolling_sum():
    """``math.sum`` in Pine. Used by the efficiency ratio's denominator
    (docs/01 section 6)."""
    src = pd.Series([1.0, 2.0, 3.0, 4.0, 5.0])
    result = p.rolling_sum(src, 3)

    assert result.iloc[:2].isna().all()
    np.testing.assert_allclose(result.iloc[2:], [6.0, 9.0, 12.0], atol=1e-12)


# ── RSI ─────────────────────────────────────────────────────────────────────────


def test_rsi_hand_computed():
    """length 2, so alpha = 1/2 and every smoothing step is a plain average.

    src   = [10, 11, 12, 11, 13]
    gain  = [na,  1,  1,  0,  2]      loss = [na, 0, 0, 1, 0]
    rma(gain, 2) = [na, na, 1.0, 0.5,  1.25]     (seed = mean(1,1))
    rma(loss, 2) = [na, na, 0.0, 0.5,  0.25]     (seed = mean(0,0))
    rs           = [na, na, inf, 1.0,  5.0]
    rsi          = [na, na, 100, 50,   83.333...]
    """
    src = pd.Series([10.0, 11.0, 12.0, 11.0, 13.0])
    result = p.rsi(src, 2)

    assert result.iloc[:2].isna().all()
    assert result.iloc[2] == pytest.approx(100.0), "all gains, no losses -> rs = inf"
    assert result.iloc[3] == pytest.approx(50.0), "equal average gain and loss"
    assert result.iloc[4] == pytest.approx(100.0 - 100.0 / 6.0)


def test_rsi_is_bounded():
    rng = np.random.default_rng(41)
    src = pd.Series(100.0 + np.cumsum(rng.normal(0, 1, 500)))
    values = p.rsi(src, 14).dropna()

    assert values.min() >= 0.0
    assert values.max() <= 100.0


def test_rsi_seeds_from_bar_one_not_bar_zero():
    """The gain/loss series is na at bar 0 (no previous close), so an RSI of
    length n first prints at bar n, not n-1."""
    src = pd.Series(np.arange(1.0, 21.0))
    result = p.rsi(src, 5)

    assert result.iloc[:5].isna().all()
    assert pd.notna(result.iloc[5])


# ── percentrank / correlation are covered in their own files ───────────────────
# ── pivots are covered in test_pivot_lag.py ────────────────────────────────────


# ── crossover / crossunder ──────────────────────────────────────────────────────


def test_crossover_requires_a_transition_not_merely_being_above():
    a = pd.Series([1.0, 2.0, 3.0, 2.0, 1.0])
    b = pd.Series([2.0, 2.0, 2.0, 2.0, 2.0])
    result = p.crossover(a, b)

    assert result.tolist() == [False, False, True, False, False]


def test_crossunder_mirrors_crossover():
    a = pd.Series([1.0, 2.0, 3.0, 2.0, 1.0])
    b = pd.Series([2.0, 2.0, 2.0, 2.0, 2.0])
    result = p.crossunder(a, b)

    assert result.tolist() == [False, False, False, False, True]


def test_touching_the_level_is_not_a_cross():
    """docs/02 section 3 entries use crossover(score, enterTh). A score that rises
    to exactly the threshold and stops has not crossed it."""
    a = pd.Series([1.0, 2.0, 2.0])
    b = pd.Series([2.0, 2.0, 2.0])

    assert not p.crossover(a, b).any()


def test_crossover_is_a_single_bar_event():
    """It fires once on the transition, not for the whole time a > b. This is why
    a gate that is false on exactly that bar loses the signal permanently --
    docs/11_FINDINGS.md finding 2."""
    a = pd.Series([1.0, 3.0, 4.0, 5.0])
    b = pd.Series([2.0, 2.0, 2.0, 2.0])

    assert p.crossover(a, b).sum() == 1


# ── valuewhen ───────────────────────────────────────────────────────────────────


def test_valuewhen_occurrence_zero_is_the_most_recent():
    cond = pd.Series([False, True, False, True, False])
    src = pd.Series([1.0, 2.0, 3.0, 4.0, 5.0])
    result = p.valuewhen(cond, src, 0)

    assert pd.isna(result.iloc[0]), "nothing has been true yet"
    np.testing.assert_allclose(result.iloc[1:], [2.0, 2.0, 4.0, 4.0], atol=1e-12)


def test_valuewhen_occurrence_one_is_the_one_before():
    """pine/AZIMUTH.pine:142-145 compares occurrences 0 and 1 to detect divergence
    between consecutive pivots."""
    cond = pd.Series([False, True, False, True, False])
    src = pd.Series([1.0, 2.0, 3.0, 4.0, 5.0])
    result = p.valuewhen(cond, src, 1)

    assert result.iloc[:3].isna().all(), "only one occurrence so far"
    np.testing.assert_allclose(result.iloc[3:], [2.0, 2.0], atol=1e-12)


def test_valuewhen_includes_the_current_bar():
    cond = pd.Series([False, True])
    src = pd.Series([1.0, 2.0])

    assert p.valuewhen(cond, src, 0).iloc[1] == pytest.approx(2.0)


def test_valuewhen_rejects_a_negative_occurrence():
    cond = pd.Series([True, True])
    src = pd.Series([1.0, 2.0])

    with pytest.raises(ValueError, match="occurrence"):
        p.valuewhen(cond, src, -1)


# ── fixnan ──────────────────────────────────────────────────────────────────────


def test_fixnan_holds_the_last_value():
    src = pd.Series([np.nan, 5.0, np.nan, np.nan, 7.0, np.nan])
    result = p.fixnan(src)

    assert pd.isna(result.iloc[0]), "nothing to carry yet"
    np.testing.assert_allclose(result.iloc[1:], [5.0, 5.0, 5.0, 7.0, 7.0], atol=1e-12)


# ── argument validation ─────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    ("fn", "length"),
    [
        (p.sma, 0),
        (p.ema, 0),
        (p.rma, 0),
        (p.stdev, 1),
        (p.rsi, 1),
        (p.percentrank, 0),
        (p.correlation, 1),
    ],
)
def test_lengths_below_the_minimum_are_rejected(fn, length: int):
    """Fail loudly rather than returning an all-NaN series that looks like a
    warm-up region and gets silently discarded by the burn-in."""
    src = pd.Series(np.arange(20.0))
    with pytest.raises(ValueError, match="length"):
        fn(src, src, length) if fn is p.correlation else fn(src, length)


def test_index_and_name_are_preserved():
    """Downstream code joins these series on a DatetimeIndex; losing it would
    misalign every component."""
    index = pd.date_range("2020-01-01", periods=30, freq="1h", tz="UTC")
    src = pd.Series(np.arange(30.0), index=index, name="close")

    for result in (p.ema(src, 5), p.rsi(src, 5), p.percentrank(src, 5), p.sma(src, 5)):
        pd.testing.assert_index_equal(result.index, index)
